# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'trainingProject' do
  pod 'AppCenterReactNativeShared', '~> 1.8.1'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for trainingProject

  

  platform :ios, '9.0'
  target 'trainingProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'trainingProject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for trainingProject-tvOS

  target 'trainingProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
